### PR TITLE
Fix link[s]

### PR DESCRIPTION
**Pull request by PallHaraldsson**
[skip ci]

### CODE REVIEW

**Comment by PallHaraldsson** [comment]
I tried to use the other package at the time, it worked, but then I needed extrapolation too, so I went with SciPy (and PyCall). I think I have the correct link for it.

**Comment by gerlero** [comment]
@PallHaraldsson thanks for the contribution! I just started this fork so that I could [get the package into the official registry](https://github.com/JuliaRegistries/General/pull/41294), plus add integration functionality that I needed. What kind of extrapolation do you require? TBH I don't currently have a use for extrapolation but I'll happily merge a PR that adds such functionality.

**Comment by PallHaraldsson** [comment]
Right, I didn't make such a PR at the time, just took the easier route to use SciPy, so having exactly the same (and same API) would be nice (I was converting code from MATLAB, and believe the extrapolation is the same, just standardized). I didn't look into how it's implemented in SciPy (or MATLAB/Octave), and don't add it just on my account. My code works. I searched for extrapolate in your code, just wanted to know I wasn't overlooking.

**Comment by gerlero** [comment]
All right! Thanks for the pointers regarding SciPy and MATLAB. I'll hold off on adding any extrapolation functionality until someone wants to start a PR or I stumble upon a use case of my own.

**Pull request merged**
